# nginx proxy address - http://172.17.0.1:8080

name: hasura
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: hasura/graphql-engine:latest
    container_name: hasura-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
    ports:
      - '172.17.0.1:8080:8080'
    volumes:
      - './rootfs/data/hasura:/data'
    networks:
      - hasura

networks:
  hasura:
    name: hasura
    external: false
